server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This line redirects all missing files to index.html so Vue Router can take over
        try_files $uri $uri/ /index.html;
    }
}