server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 100M;

    location / {
        # This line redirects all missing files to index.html so Vue Router can take over
        try_files $uri $uri/ /index.html;
    }
    
    location /api {
        resolver 8.8.8.8 8.8.4.4 valid=30s;
        set $backend_url https://backend-web-service-b2ng.onrender.com;

        proxy_pass $backend_url;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
